// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAadeXNQjnw8SOPgjHfkzu36hj2gn701ro',
    appId: '1:295698182170:web:3f9802eaf54575537561a3',
    messagingSenderId: '295698182170',
    projectId: 'webadmin-e8d1a',
    authDomain: 'webadmin-e8d1a.firebaseapp.com',
    storageBucket: 'webadmin-e8d1a.appspot.com',
    measurementId: 'G-MSSKYQTNT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-RzRQv6t25Ch1bRWhT352QjI-6X_tnGY',
    appId: '1:295698182170:android:4bb38baa0e018cbb7561a3',
    messagingSenderId: '295698182170',
    projectId: 'webadmin-e8d1a',
    storageBucket: 'webadmin-e8d1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHMwvu4cyDYpE5r1BjGx-Y1rSDB2TSFpI',
    appId: '1:295698182170:ios:97e1974d217791587561a3',
    messagingSenderId: '295698182170',
    projectId: 'webadmin-e8d1a',
    storageBucket: 'webadmin-e8d1a.appspot.com',
    iosBundleId: 'com.example.webadmin',
  );


  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHMwvu4cyDYpE5r1BjGx-Y1rSDB2TSFpI',
    appId: '1:295698182170:ios:e72065c2beb5d96a7561a3',
    messagingSenderId: '295698182170',
    projectId: 'webadmin-e8d1a',
    storageBucket: 'webadmin-e8d1a.appspot.com',
    iosBundleId: 'com.example.webadmin.RunnerTests',
  );
}
