// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5gAeVhXajzRJEVeE19Wsl1fEK8GiRScA',
    appId: '1:684384820410:web:f3fda49be7820a7c1a3683',
    messagingSenderId: '684384820410',
    projectId: 'uberclone-d6cc2',
    authDomain: 'uberclone-d6cc2.firebaseapp.com',
    storageBucket: 'uberclone-d6cc2.appspot.com',
    measurementId: 'G-N0QGSB8HZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBG0prWaU-YrSzxwm6epI3LkaPHlDVt6U',
    appId: '1:684384820410:android:8d3be93a6247dabc1a3683',
    messagingSenderId: '684384820410',
    projectId: 'uberclone-d6cc2',
    storageBucket: 'uberclone-d6cc2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLdsZN46K2eihprp3_QERpqRo_6yAT1Xw',
    appId: '1:684384820410:ios:312762fb9e3005c81a3683',
    messagingSenderId: '684384820410',
    projectId: 'uberclone-d6cc2',
    storageBucket: 'uberclone-d6cc2.appspot.com',
    iosBundleId: 'com.example.uberShopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLdsZN46K2eihprp3_QERpqRo_6yAT1Xw',
    appId: '1:684384820410:ios:4c90defdeafac1f71a3683',
    messagingSenderId: '684384820410',
    projectId: 'uberclone-d6cc2',
    storageBucket: 'uberclone-d6cc2.appspot.com',
    iosBundleId: 'com.example.uberShopApp.RunnerTests',
  );
}
